### ISSUE TITLE
Could not install pipenv: exit status 1

### ISSUE THREAD

**Issue by rogeruiz** [cloudfoundry/python-buildpack#101] opened 2018-03-28 21:52 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```shell
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.fr.cloud.gov",
   "token_endpoint": "https://uaa.fr.cloud.gov",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.106.0",
   "app_ssh_endpoint": "ssh.fr.cloud.gov:2222",
   "app_ssh_host_key_fingerprint": "fd:99:34:45:f5:b8:3f:fc:bf:a0:67:cd:ba:10:75:52",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.fr.cloud.gov:443"
}
cf version 6.34.1+bbdf81482.2018-01-17
```

What version of the buildpack you are using?

```shell
-----> Python Buildpack version 1.6.11
```

If you were attempting to accomplish a task, what was it you were attempting to do?

```shell
cf push
```

What did you expect to happen?

Application deployed successfully.

What was the actual behavior?

```shell
# ... removed for brevity / security
-----> Installing pipenv 11.1.4
       Download [https://buildpacks.cloudfoundry.org/dependencies/pipenv/pipenv-v11.1.4-7394418e.tgz]
       Generating 'requirements.txt' with pipenv
Traceback (most recent call last):
  File "/tmp/contents126611305/deps/0/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.1.4', 'console_scripts', 'pipenv')()
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/cli.py", line 238, in lock
    core.ensure_project(three=three, python=python)
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/core.py", line 638, in ensure_project
    crayons.green(shorten_path(path_to_python))
TypeError: __str__ returned non-string (type NoneType)
       **ERROR** Could not install pipenv: exit status 1
Failed to compile droplet: Failed to run all supply scripts: exit status 14
# ... removed for brevity / security
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sclevine** [comment] 2018-03-28 21:56
Can you provide a sample app that produces this error?

**Comment by rogeruiz** [comment] 2018-03-28 22:27
https://github.com/18f/tock on the `master` branch @sclevine

**Comment by rogeruiz** [comment] 2018-03-29 12:21
@sclevine an engineer on our team mentioned that it seems like it's breaking while it's generating the `requirements.txt`. cc: @Jkrzy

**Comment by sclevine** [comment] 2018-03-29 14:07
Thanks! Prioritizing now.

**Comment by astrieanna** [comment] 2018-03-29 14:38
@rogeruiz We're working on reproducing this issue, and have a couple questions.
- are you using only the python buildpack for this app, or multiple buildpacks?
- we noticed that `tock` has a requirements.txt file in the repo; is that not there when you're pushing the app?

**Comment by ameyer-pivotal** [comment] 2018-03-29 14:54
@rogeruiz Our guess is that perhaps something is messing with your python version. Looking at the stack trace you posted, we found the relevant code in Pipenv. It looks like it's in the middle of trying to warn you about the python version:

https://github.com/pypa/pipenv/blob/9b5f5338277cb42382f147f92f2e5163e3a547f4/pipenv/core.py#L638

**Comment by rogeruiz** [comment] 2018-03-29 15:57
@astrieanna 

> are you using only the python buildpack for this app, or multiple buildpacks?

Just the python build pack. We recently migrated from using `requirements.txt` and `pip` to `pipenv`.

> we noticed that tock has a requirements.txt file in the repo; is that not there when you're pushing the app?

That was just added a few hours ago. But ideally, we'd like to have that not pushed up by adding it to the `.cfignore` as we only generate it for dependency management tooling. But it seems like we need to push it up for the build pack to be successful.

> could you post a bit more of the output, starting from installing python?

Sure, here's the output.

<details>
<summary>Failed deployment output</summary>

```shell
#!/bin/bash -eo pipefail
cf login -a ${CF_API} -u ${CF_DEPLOYER_USERNAME_STAGING} -p ${CF_DEPLOYER_PASSWORD_STAGING}
echo ${CIRCLE_SHA1} > tock/VERSION
cf_deploy.sh tock gsa-18f-tock staging manifest-staging.yml
API endpoint: https://api.fr.cloud.gov
Authenticating...
OK

Targeted org gsa-18f-tock

Targeted space staging


                
API endpoint:   https://api.fr.cloud.gov (API version: 2.106.0)
User:           service-account@cloud.gov
Org:            gsa-18f-tock
Space:          staging
+ app=tock
+ org=gsa-18f-tock
+ space=staging
+ manifest=manifest-staging.yml
+ [[ -z gsa-18f-tock ]]
+ [[ -z staging ]]
+ [[ -z tock ]]
+ [[ ! -r manifest-staging.yml ]]
+ [[ -n https://api.fr.cloud.gov ]]
+ cf api https://api.fr.cloud.gov
Setting api endpoint to https://api.fr.cloud.gov...
OK

api endpoint:   https://api.fr.cloud.gov
api version:    2.106.0
+ set +x
+ cf target -o gsa-18f-tock -s staging
api endpoint:   https://api.fr.cloud.gov
api version:    2.106.0
user:           ████████████████████
org:            gsa-18f-tock
space:          staging
+ cf zero-downtime-push tock -f manifest-staging.yml
Renaming app tock to tock-venerable in org gsa-18f-tock / space staging as ████████████████████...
OK
Using manifest file manifest-staging.yml

Using stack cflinuxfs2...
OK
Creating app tock in org gsa-18f-tock / space staging as ████████████████████...
OK

Using route tock.app.cloud.gov
Binding tock.app.cloud.gov to tock...
OK

Using route tock.app.cloud.gov/api
Binding tock.app.cloud.gov/api to tock...
OK

Uploading tock...
Uploading app files from: /root/repo
Uploading 420.6K, 468 files

Done uploading
OK
Binding service tock-database to app tock in org gsa-18f-tock / space staging as ████████████████████...
OK
Binding service tock-credentials to app tock in org gsa-18f-tock / space staging as ████████████████████...
OK

Starting app tock in org gsa-18f-tock / space staging as ████████████████████...
Downloading python_buildpack...
Downloaded python_buildpack
Cell ████████████████████ creating container for instance ████████████████████
Cell ████████████████████ successfully created container for instance ████████████████████
Downloading app package...
Downloaded app package (2.1M)
-----> Python Buildpack version 1.6.11
-----> Supplying Python
-----> Installing python 3.6.4
       Download [https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.4-linux-x64-8932d266.tgz]
-----> Installing setuptools 38.5.2
       Download [https://buildpacks.cloudfoundry.org/dependencies/setuptools/setuptools-38.5.2-8246123e.zip]
-----> Installing pip 9.0.1
       Download [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip/pip-9.0.1-35f01da3.tar.gz]
-----> Installing pip-pop 0.1.1
       Download [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip-pop/pip-pop-0.1.1-d410583a.tar.gz]
-----> Installing pipenv 11.1.4
       Download [https://buildpacks.cloudfoundry.org/dependencies/pipenv/pipenv-v11.1.4-7394418e.tgz]
       Generating 'requirements.txt' with pipenv
Traceback (most recent call last):
  File "/tmp/contents126611305/deps/0/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.1.4', 'console_scripts', 'pipenv')()
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/cli.py", line 238, in lock
    core.ensure_project(three=three, python=python)
  File "/tmp/contents126611305/deps/0/python/lib/python3.6/site-packages/pipenv/core.py", line 638, in ensure_project
    crayons.green(shorten_path(path_to_python))
TypeError: __str__ returned non-string (type NoneType)
       **ERROR** Could not install pipenv: exit status 1
Failed to compile droplet: Failed to run all supply scripts: exit status 14
Exit status 223
Cell ████████████████████ stopping instance ████████████████████
Cell ████████████████████ destroying container for instance ████████████████████
Cell ████████████████████ successfully destroyed container for instance ████████████████████

Deleting app tock in org gsa-18f-tock / space staging as ████████████████████...
OK
Renaming app tock-venerable to tock in org gsa-18f-tock / space staging as ████████████████████...
OK
error: Error restarting application: BuildpackCompileFailed

TIP: use 'cf logs tock --recent' for more information
Exited with code 1
```
</details>

**Comment by rogeruiz** [comment] 2018-03-29 15:59
Interesting, @ameyer-pivotal. Thanks for the link to the source. Seems like this could potentially be an issue in `pipenv`, right? I can go ahead and open an issue over there regarding this. Doesn't seem like it should be choking on printing out the python version.

**Comment by astrieanna** [comment] 2018-03-29 19:03
We're still struggling to reproduce this, despite the same versions (including of python and pipenv). We cloned tock, removed requirements.txt, and pushed. We're services/config to make the app actually start successfully but it definitely gets past pipenv.

Our theory is that there must be some extra state that we're not reproducing that's causing this issue. Just to make sure it's in your environment or config and not some state in your local git repo, could you `git clone` tock to a new folder and `cf push` to a space that does not already have an instance of `tock`? If it starts working for you in that situation, then there must be some state in your setup that is causing pipenv issues with figuring out your python version.

**Comment by rogeruiz** [comment] 2018-03-29 21:51
I'm struggling here too @astrieanna. It looks like it's a fluke? I'm able to deploy a new version of the application from a fresh clone following the steps below. It's making it past the `pipenv` installation. I'm not sure what the issue was considering this wasn't happening locally, but rather in our CircleCI `build_and_deploy` workflow. The Docker image that uses to build the project is `circleci/python:3.6.4-jessie-node-browsers` which is the same version I have installed locally.

```shell
cd $(mktemp -d)
git clone https://github.com/18f/tock
git checkout 50ac38cb2ae1837feeccb08a742b98ba314f6a72
pip install pipenv
pipenv install --dev --deploy
npm install
cf push tock-test -f manifest-staging.yml
```

**Comment by ameyer-pivotal** [comment] 2018-03-30 13:48
@rogeruiz Interesting. OK, well we'll close this for now and feel free to bring it up again if you find you're able to reproduce it consistently.

**Closed by ameyer-pivotal** 2018-03-30 13:48 UTC
Labels: in progress

**Comment by rogeruiz** [comment] 2018-04-03 19:51
This issue has popped up again. This time after we added the `requirements.txt` to the `.cfignore`. I don't think there are any artifacts popping up here that are causing the issue. but it's certainly happening because of `pipenv`. Not sure what's happening here.

**Comment by rogeruiz** [comment] 2018-04-03 20:42
We're using CircleCI to deploy this to a cloud foundry instance and it's using the latest python build pack.

**Comment by semiversus** [comment] 2018-09-14 23:34
This problem also occurred to us and it was reported here: https://github.com/pypa/pipenv/issues/2609 .
