### ISSUE TITLE
python3.8.12 - fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by sunny-repo88** [cloudfoundry/python-buildpack#574] opened 2022-08-22 14:46 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
`cf8.exe version 8.2.0+fd8fbca64.2022-02-09
`

What version of the buildpack you are using?
`https://github.com/cloudfoundry/python-buildpack#v1.7.49
`

What did you expect to happen?
`Install xmlsec succesfully in  python 3.8.12 - https://github.com/mehcode/python-xmlsec`

What was the actual behavior?
- Able to install xmlsec in python 3.6.15
- Unable to install xmlsec in python 3.8.12 with error log below
![image](https://user-images.githubusercontent.com/30856837/185949626-3cd2c7d9-44dd-46f1-80c8-b0132bf88725.png)

Steps to reproduce:
`git clone https://github.com/sunny-repo88/cf-python-buildpack-bug; cd cf-python-buildpack-bug;cf push
`

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by arjun024** [comment] 2022-08-22 15:28
From a super quick look, it looks like not an issue with the python buildpack, but the [apt-buildpack](https://github.com/cloudfoundry/apt-buildpack) not meeting your expectations.

I can take a look but I want to remind you that APT buildpack is an experimental buildpack expected to only work for very simple packages (e.g., a single shared lib with no data)

**Comment by amhuber** [comment] 2022-08-22 17:05
We are also seeing this on our environments.  We haven't figured out what changed yet, but apps that were previously deploying are now getting this error, and the apt.yml packages were set up correctly to support compilation of xmlsec.

**Comment by amhuber** [comment] 2022-08-22 18:53
The compilation does work on Python 3.6, but any version after that is broken.  Steps to reproduce using https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop/assets/python with the following modifications:

**apt.yml**

    ---
    packages:
    - libxml2-dev
    - libxmlsec1-dev
    - libxmlsec1-openssl

**requirements.txt**

    xmlsec

**runtime.txt**

    python-3.6.x

Push with an older buildpack to get 3.6 support:

    cf push pytest01 -b https://github.com/cloudfoundry/apt-buildpack.git -b https://github.com/cloudfoundry/python-buildpack.git#v1.7.49

Using 3.7 or higher results in the missing Python.h error.

**Comment by sunny-repo88** [comment] 2022-08-23 01:52
@arjun024 , thanks for quick response. I have another example without using apt buildpack

Steps to reproduce:
```
git clone https://github.com/sunny-repo88/cf-python-buildpack-withoutapt
cd cf-python-buildpack-withoutapt ;cf push
```


Behaviour:
```
Able to install psycopg2 in python 3.6.15
Unable to install psycopg2 in python 3.8.12 with error log below
```

**We are able to install both example in fresh new docker environment - python:3.8-buster**


![image](https://user-images.githubusercontent.com/30856837/186050920-26d28219-bcdb-49af-997e-d8b84a4e8a1a.png)

**Comment by risicle** [comment] 2022-08-23 09:30
Hi, FWIW we also have two separate tenants having similar problems who "changed nothing" and now their native extensions won't build, not being able to find `Python.h`. In these cases the packages are `pycurl` and `ciso8601`. Multiple recent python-buildpack versions tried. Python 3.7 & 3.9.

Last known successful build was on the 17th Aug.

**Comment by a09-capf** [comment] 2022-08-23 10:17
I face the same issue.
I use Python 3.8.10 & psycopg2 2.9.3 and "changed nothing" since 8th Aug.

**Comment by Deviaruna** [comment] 2022-08-23 11:06
Hi All,
We were facing the same issue in multiple projects. One of our colleague has figured out the reason behind the crash.
One transient package upgraded i.e. setuptools from 65.1 to 65.2 version. If you could downgrade setuptools to 65.1.0, that would work.
Thanks

**Comment by rjbaker** [comment] 2022-08-23 12:08
We build `pycurl` from source during the droplet build and started encountering errors with `Python.h` not being found.

I've also managed to work around this by pinning `setuptools==65.1.1` thanks to @Deviaruna.

Oddly our last successful droplet build on 17th August installed setuptools 65.0.2 as a transient package. Only explicitly pinning setuptools now produces a successful build.

**Comment by sunny-repo88** [comment] 2022-08-23 14:57
By pinning `setuptools==65.1.1`. I am to build  `psycopg2`  from source.
But still seeing same issue on 'xmlsec'.

I dont think setuptools is the main cause of this issue.
As stated in, 
https://github.com/cloudfoundry/python-buildpack/blob/master/manifest.yml#L130

setuptools  v63.4.2 was used in latest buildpack. is far behind than 65.2.0

@arjun024 , let me know if i am pointing to the wrong file

**Comment by arjun024** [comment] 2022-08-23 15:28
Like @Deviaruna said, this issue seems to be caused by a setuptools version downloaded as a transitive dependency by users' direct dependencies (e.g. psycopg2), and not due to a dependency provided by the buildpack. For the same app, I can see this same issue occurring while using an older version. I'm not sure buildpacks have control over it though I can look into it if there's something we can do.

@sunny-repo88 For https://github.com/cloudfoundry/python-buildpack/blob/master/manifest.yml#L130, this works for me:

```diff
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,3 +1,4 @@
 Flask==2.0.1
 gunicorn==20.1.0
+setuptools==65.1.1^M
 psycopg2==2.9.1
```

**Comment by amhuber** [comment] 2022-08-23 16:48
Keeping setuptools permanently pinned to an old version isn't going to work forever.  I'm hoping there are some updates that can be made to the buildpack to adjust to whatever setuptools is expecting.  It looks like https://github.com/heroku/heroku-buildpack-python/commit/b2dfe7397bf2f57b70799954277dd01a9c034432 might be related.

**Comment by mrogaski** [comment] 2022-08-23 19:38
> Additionally, @amhuber , thanks for sharing that Heroku link. It is interesting, but I don't think it's the complete answer as it only applies when apps are using `pyproject.toml` in conjunction with newer versions of `setuptools`, and some users in this thread are reporting this issue without having a `pyproject.toml` at all.

It affects krb5 0.3.0, too.  That project only moved to pyproject.toml in 0.4.0.

**Comment by amhuber** [comment] 2022-08-24 07:46
> It affects krb5 0.3.0, too. That project only moved to pyproject.toml in 0.4.0.

Exactly, it's not the customer code using a `pyproject.toml` file that is the issue, it's when the package being installed does, and obviously customers have no control over that.

**Comment by robdimsdale** [comment] 2022-08-24 12:50
@mrogaski @amhuber yes, agreed. We believe that when an application depends on a project that uses [PEP-517 Build Isoloation](https://peps.python.org/pep-0517/) - like `krb5` has done since its creation - and that project has a build-dependency on `setuptools` without an upper limit (like `krb5`) then the latest version of `setuptools` (i.e. `65.2.0`) is downloaded and we observe the same issue as if the app had `setuptools` as a direct dependency.

We are actively exploring a fix for the root cause - `setuptools >= 65.2.0` not working with the python buildpack - as well as any potential workarounds to assist with pinning the version of `setuptools` when it is pulled in as a transitive dependency. We will keep this thread updated with our investigation.

**Comment by robdimsdale** [comment] 2022-08-24 14:50
We are able to reproduce the underlying issue a few different ways, and we have a fix for the root case on the `develop` branch.

You can try this out by using the `develop` branch while pushing your app:

```
cf push <args> -b https://github.com/cloudfoundry/python-buildpack#develop
```

Please try this out and let us know if it works (or doesn't work).

We expect to release a new version of the buildpack shortly, but any feedback before then would be welcome.

**Comment by amhuber** [comment] 2022-08-24 15:57
I can confirm that xmlsec now compiles correctly using the repro steps above.  Thanks for the quick fix!

**Comment by sunny-repo88** [comment] 2022-08-24 23:43
Confirmed. Issue resolved in https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.58.

Thanks to the team!

**Comment by robdimsdale** [comment] 2022-08-25 14:09
Yes, as @sunny-repo88 highlights, we have shipped https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.58 with a fix for the underlying issue.

There should be no reason to continue pinning `setuptools=65.1.1` in application dependencies - we should once again be able to support the latest version of `setuptools`.

Thank you everyone for your patience, and for your help in diagnosing, reproducing, and ultimately fixing the issue.

**Comment by arjun024** [comment] 2022-08-25 14:56
Regarding `mercurial` pre-installation, it looks that step came in to the python CF buildpack via its forking of the original heroku buildpack. Since then it looks like they removed it in 2020 https://github.com/heroku/heroku-buildpack-python/pull/1111/

Pip documentation ([link](https://pip.pypa.io/en/latest/topics/vcs-support)) just states that it requires a working executable to be available, which
already exists on the stack.
```
‣ docker run --init -it cloudfoundry/cflinuxfs3 bash -c "hg --version"
Mercurial Distributed SCM (version 4.5.3)
```

**Comment by arjun024** [comment] 2022-08-26 19:06
I'm closing this issue with the release of v1.7.58. If you're still facing the same issue, please feel free to reopen with logs & a sample app.

**Closed by arjun024** 2022-08-26 19:06 UTC
Labels: unscheduled
