### ISSUE TITLE
Pushing Flask applications is failing with error msg : Unable to rewrite she-bangs: open ..../pip-grep: text file busy

### ISSUE THREAD

**Issue by alexquitiaquez** [cloudfoundry/python-buildpack#314] opened 2021-05-21 23:12 UTC
#### What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
Tested with CF CLI versions 6.53.0 ans 6.52.0

#### What version of the buildpack you are using?

Tested in buildpack versions v1.7.29, v1.7.30 and v1.7.39

#### If you were attempting to accomplish a task, what was it you were attempting to do?

We were trying to push some python applications (REST API's) based on Flask and they started to fail approx. last week, so we decided to try with a simpler App in order to reproduce the problem easily and it failed as well.

Here that simple Flask application (API), the code and the files used to deploy,
**hello.py**
```python
from flask import Flask
from markupsafe import escape
app = Flask(__name__)
@app.route('/')
def hello_world():
    return 'Hello, World!'
@app.route('/hello/<username>')
def hello_user(username):
    # say hello to that user
    return 'Hello %s' % escape(username)
```
**requirements.txt**
```text
Flask==1.1.2
```
**manifest.yml**
```YAML
---
applications:
  - name: test-app-flask-minimale-dev
    memory: 512MB
    disk_quota: 256MB
    buildpacks:
      - python_buildpack
      # - https://github.com/cloudfoundry/python-buildpack#v1.7.39
    timeout: 600
```
**Procfile**
```text
web: FLASK_APP=hello.py python3 -m flask run --host=0.0.0.0 --port=$PORT
```

Here the commands used tu push the App
```shell
cf api https://<cloudfoundry-server-domain>
cf login

cf push 
```

#### What did you expect to happen?
Application should be deployed and should respond to requests to the endpoint https://test-app-flask-minimale-dev.<HOSTNAME_DOMAIN>with the text Hello, World!

#### What was the actual behavior?
We got this error message,
`**ERROR** Unable to rewrite she-bangs: open /tmp/contents928626649/deps/0/bin/pip-grep: text file busy`

here a the full log,

```shell
$ cf push
Pushing from manifest to org *************-org / space dev as USER...   
Using manifest file C:\DEV\projets\PaaS\test-app-flask-minimale\manifest.yml
Getting app info...
Updating app with these attributes...
  name:                   test-app-flask-minimale-dev
  path:                   C:\DEV\projets\PaaS\test-app-flask-minimale
  buildpacks:
    python_buildpack
  command:                FLASK_APP=hello.py python3 -m flask run --host=0.0.0.0 --port=$PORT
  disk quota:             256M
  health check timeout:   600
  health check type:      port
  instances:              1
  memory:                 512M
  stack:                  cflinuxfs3
  routes:
    test-app-flask-minimale-dev.*******************************

Updating app test-app-flask-minimale-dev...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 1.60 KiB / 1.60 KiB [=====================================================================================================] 100.00% 1s 

Waiting for API to complete processing files...

Stopping app...

Staging app and tracing logs...
   Downloading python_buildpack...
   Downloaded python_buildpack
   Cell b6f1b8ef-c1dd-452e-9fd4-ba2c89aa4593 creating container for instance 1a6afc1d-bee3-466a-a61f-58a62c24f974
   Cell b6f1b8ef-c1dd-452e-9fd4-ba2c89aa4593 successfully created container for instance 1a6afc1d-bee3-466a-a61f-58a62c24f974
   Downloading app package...
   Downloading build artifacts cache...
   Downloaded app package (1.6K)
   Downloaded build artifacts cache (2.9M)
   -----> Python Buildpack version 1.7.29
   -----> Supplying Python
   -----> Installing python 3.8.7
          Copy [/tmp/buildpacks/c1728e37466eeca3a6f3cf36beac3bf3/dependencies/d0d75bcb12e9ab4d4c7af3492e42dc04/python_3.8.7_linux_x64_cflinuxfs3_4abd87d1.tgz]
   -----> Installing pip-pop 0.1.5
          Copy [/tmp/buildpacks/c1728e37466eeca3a6f3cf36beac3bf3/dependencies/2e88c958cb5cf0638aa875fa2e7b99e0/pip-pop-0.1.5-b32efe86.tar.gz]
   -----> Running Pip Install
          Collecting Flask==1.1.2
            Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
          Collecting itsdangerous>=0.24
            Using cached itsdangerous-2.0.1-py3-none-any.whl (18 kB)
          Collecting click>=5.1
            Using cached click-8.0.1-py3-none-any.whl (97 kB)
          Collecting Jinja2>=2.10.1
            Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
          Collecting Werkzeug>=0.15
            Using cached Werkzeug-2.0.1-py3-none-any.whl (288 kB)
          Collecting MarkupSafe>=2.0
            Using cached MarkupSafe-2.0.1-cp38-cp38-manylinux2010_x86_64.whl (30 kB)
          Installing collected packages: itsdangerous, click, MarkupSafe, Jinja2, Werkzeug, Flask
            WARNING: The script flask is installed in '/tmp/contents628900793/deps/0/python/bin' which is not on PATH.
            Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
          Successfully installed Flask-1.1.2 Jinja2-3.0.1 MarkupSafe-2.0.1 Werkzeug-2.0.1 click-8.0.1 itsdangerous-2.0.1
          WARNING: You are using pip version 20.2.3; however, version 21.1.1 is available.
          You should consider upgrading via the '/tmp/contents628900793/deps/0/bin/python -m pip install --upgrade pip' command.        
          **ERROR** Unable to rewrite she-bangs: open /tmp/contents628900793/deps/0/bin/pip-grep: text file busy
Error staging application: App staging failed in the buildpack compile phase
FAILED
```

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by jjghali** [comment] 2021-05-25 14:30
I have the same issue as @alexquitiaquez. I had to downgrade to v1.7.26 of the buildpack in order to be able to use it.

**Comment by ukabu** [comment] 2021-06-01 13:28
It seems that only the python buildpack make this kind of she-bang modification. I think it would be better to skip that step. But it may be a breaking change for a number of deployements, so I guess it is going to stay there.

I would suggest to make the change in a safer way, by moving the original file first, then writing the modified one.

Maybe a better way yet, would be to install package only required by the buildpack in a different (temporary) virtual environment so that it does not interfere with package required by the app.

**Comment by menehune23** [comment] 2021-09-08 22:28
@alexquitiaquez Thanks for reporting this. I'll see if I can reproduce it with the code you provided.

I know it's been a couple of months since you posted this. We're heavily focused on the newer container-centric [Paketo Python buildpack](https://github.com/paketo-buildpacks/python), so if you happen to have a workaround or solution by now that you'd be interested in PRing into this repo, we'd be happy to take a look. We unfortunately don't have as much bandwidth to prioritize the CF buildpacks as we would like.

**Comment by menehune23** [comment] 2021-09-08 23:17
@alexquitiaquez I `cf push`ed the code you provided, in combination with the latest buildpack (`v1.7.45`), and the app stages successfully. I'm able to open it in a browser and get a "Hello, World" response.

I'll close this for now as it seems to be resolved by the latest buildpack, but feel free to reopen if that's not your experience.

For reference:

`cf curl /v2/info && cf version`:
```
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.phlox.cf-app.com",
   "token_endpoint": "https://uaa.phlox.cf-app.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "ssh.phlox.cf-app.com:2222",
   "app_ssh_host_key_fingerprint": "dnAG2+RAAk0HauyuHF0eiSPEFbZjtZyIdjfTWdRb4TE",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.phlox.cf-app.com:443",
   "api_version": "2.169.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.phlox.cf-app.com/routing",
   "user": "e3c4af9d-7272-4188-9e11-e47c9ee7f994"
}
cf version 6.53.0+8e2b70a4a.2020-10-01
```

**Closed by menehune23** 2021-09-08 23:17 UTC
Labels: unscheduled
