### ISSUE TITLE
Pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available

### ISSUE THREAD

**Issue by Dillon-Based** [cloudfoundry/python-buildpack#620] opened 2022-10-10 17:32 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "***",
   "token_endpoint": "***",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "***",
   "app_ssh_host_key_fingerprint": "***",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "***",
   "api_version": "2.124.0",
   "osbapi_version": "2.14",
   "user": "0d2d3c6b-4af3-4516-9111-8653faa32c9f"
}
cf version 6.53.0+8e2b70a4a.2020-10-01

What version of the buildpack you are using?
1.8.1

If you were attempting to accomplish a task, what was it you were attempting to do?
Stage app with python 3.10.x

What did you expect to happen?
app installed with 3.10.X

What was the actual behavior?
Fails to install, says "WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available"

11:20:21.807: [STG.0] -----> Running Pip Install
11:20:25.083: [STG.0]        WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
11:20:25.085: [STG.0]        adding trusted host: '****' (from line 1 of /tmp/app/requirements.txt)
11:20:25.236: [STG.0]        Looking in links: *****
11:20:25.369: [STG.0]        WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /ctu/CTU_tools
11:20:25.870: [STG.0]        WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /ctu/CTU_tools
11:20:26.871: [STG.0]        WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /ctu/CTU_tools
11:20:28.872: [STG.0]        WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /ctu/CTU_tools
11:20:32.878: [STG.0]        WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /ctu/CTU_tools
11:20:32.879: [STG.0]        Could not fetch URL *****: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='*****', port=443): Max retries exceeded with url: /ctu/CTU_tools (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
11:20:32.881: [STG.0]        WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctu-tools/
11:20:33.384: [STG.0]        WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctu-tools/
11:20:34.385: [STG.0]        WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctu-tools/
11:20:36.386: [STG.0]        WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctu-tools/
11:20:40.390: [STG.0]        WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctu-tools/
11:20:40.391: [STG.0]        Could not fetch URL https://pypi.org/simple/ctu-tools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ctu-tools/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
11:20:40.401: [STG.0]        ERROR: Could not find a version that satisfies the requirement CTU_tools (from versions: none)
11:20:40.401: [STG.0]        ERROR: No matching distribution found for CTU_tools
11:20:40.502: [STG.0]        **ERROR** Could not install pip packages: could not run pip: exit status 1
11:20:40.796: [STG.0] Cell 07b6ddc4-7627-4179-9dc5-7e45b019da32 stopping instance e4b5900d-329c-4c3b-983c-5a3208876670
11:20:40.505: [STG.0] Failed to compile droplet: Failed to run all supply scripts: exit status 14
11:20:40.518: [STG.0] Exit status 223

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [ ] I have included steps for reproduction

I have redacted some URIs, things seem to work fine with Python 3.9.14 with the same buildpack.

**Comment by robdimsdale** [comment] 2022-10-13 22:28
Hi @Dillon-Based - what stack are you using? You can check this with `cf stacks`.

**Comment by Dillon-Based** [comment] 2022-10-18 20:52
Hi, thanks @robdimsdale it looks like we're on cflinuxfs3

**Comment by Dillon-Based** [comment] 2022-10-18 20:56
@bnitz918 I mentioned this

**Comment by niiiitz** [comment] 2022-10-20 14:45
cflinuxfs3
   Cloud Foundry Linux-based filesystem (Ubuntu 18.04)

**Comment by robdimsdale** [comment] 2022-10-25 13:18
Ok thanks.

I don't see any reason why Python 3.10 shouldn't work with Ubuntu 18.04 (Bionic), so let's try to narrow down the issue. I also can't reproduce this issue.

1. Have you successfully built this same app with this buildpack version, stack version, and python version before?
    * Have you successfully built _other_ apps with this buildpack, stack, and python version combination?
1. Have you successfully built this same app with the same buildpack/stack combinatino with a different version of python (e.g. python 3.9 or 3.8)?

**Comment by robdimsdale** [comment] 2022-10-25 13:18
Also can you share an example application to reproduce this issue with?

**Comment by robdimsdale** [comment] 2022-10-31 15:31
Ok that's helpful, thanks.

I'll try to reproduce this with Python 3.10 on cflinuxfs3.

Just FYI I don't think the version of the CF CLI is likely to be causing any issues.

**Comment by arjun024** [comment] 2022-11-29 20:14
I have tried to reproduce the issue with the given `requirements.txt` but I do not get any staging errors. (Tried with cf cli v7 as well as v6).

Used this app https://github.com/cloudfoundry/python-buildpack/tree/v1.8.3/fixtures/django_python_3 and added in the given `requirements.txt`, with `runtime.txt` reading `python-3.10.x`. Staging goes fine with Python 3.10 picked up.

If you can provide a full app, we can give it another try

**Comment by johnnyr0x** [comment] 2023-03-24 16:59
Closing as we weren't able to reproduce the issue. Feel free to re-open if you can help with those steps.

**Closed** 2023-03-24 16:59 UTC
