### ISSUE TITLE
**Release:** python-buildpack 1.7.44

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/python-buildpack#349] opened 2021-07-11 22:04 UTC
**Dependency Changes:**

```diff
No dependency changes
```

**New Commits on Develop**:

None

Refer to [release instructions](https://docs.cloudfoundry.org/buildpacks/releasing_a_new_buildpack_version.html).

**Comment by arjun024** [comment] 2021-07-14 19:02
duplicate of #352

**Closed by arjun024** 2021-07-14 19:02 UTC
Labels: unscheduled
